"""Generating project agents from the overlay.

A plugin cannot change its own agent definitions per project, and effort has no per-call
override. So a tier the project resized or added becomes `.claude/agents/router-<tier>.md`,
written from the overlay and the shipped agent body. The output is deterministic.
"""

import re
from pathlib import Path

from . import PROJECT_AGENT_PREFIX

MARKER = "<!-- Generated by agent-router from .claude/agent-router.json. Edit that file. -->"
FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n(.*)\Z", re.DOTALL)
CARRIED_FIELDS = ("maxTurns", "disallowedTools", "color")


def shipped_agents_dir():
    """The shipped agent definitions: beside the scripts when vendored, else in the plugin."""
    here = Path(__file__).resolve().parent
    for candidate in (here.parent / "agents", here.parent.parent / "agents"):
        if candidate.is_dir():
            return candidate
    raise FileNotFoundError("agent-router: shipped agent definitions not found")


def parse_agent(text):
    match = FRONTMATTER.match(text)
    if not match:
        raise ValueError("agent file has no frontmatter")
    fields = {}
    for line in match.group(1).splitlines():
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields, match.group(2)


def render(tier, base_fields, base_body, description=None):
    """The project agent file for one tier."""
    lines = [
        "---",
        f"name: {PROJECT_AGENT_PREFIX}{tier.name}",
        f"description: {description or base_fields['description']}",
        f"model: {tier.model}",
        f"effort: {tier.effort}",
    ]
    lines += [f"{key}: {base_fields[key]}" for key in CARRIED_FIELDS if key in base_fields]
    lines += ["---", "", MARKER, base_body.rstrip("\n"), ""]
    return "\n".join(lines)


def planned_files(config, descriptions=None):
    """Mapping of file name to content for every remapped or added tier."""
    descriptions = descriptions or {}
    source = shipped_agents_dir()
    files = {}
    for tier in config.tiers.values():
        if not tier.remapped:
            continue
        base = tier.name if tier.shipped else (tier.like or "worker")
        fields, body = parse_agent((source / f"{base}.md").read_text(encoding="utf-8"))
        description = descriptions.get(tier.name)
        if description is None and not tier.shipped:
            description = (
                f"Project tier `{tier.name}` ({tier.model}, {tier.effort} effort), "
                f"routed like {base}. {fields['description']}"
            )
        elif description is None:
            description = re.sub(
                r"\([^)]*\)",
                f"({tier.model}, {tier.effort} effort)",
                fields["description"],
                count=1,
            )
        files[f"{PROJECT_AGENT_PREFIX}{tier.name}.md"] = render(tier, fields, body, description)
    return files


def sync(root, config, descriptions=None):
    """Write the project agents and remove generated ones that no longer apply.

    Returns a list of human-readable changes. Files without the generated marker are never
    touched.
    """
    directory = Path(root) / ".claude" / "agents"
    directory.mkdir(parents=True, exist_ok=True)
    wanted = planned_files(config, descriptions)
    changes = []
    for name, content in sorted(wanted.items()):
        path = directory / name
        if path.is_file():
            current = path.read_text(encoding="utf-8")
            if current == content:
                continue
            if MARKER not in current:
                changes.append(f"skipped .claude/agents/{name}: not generated by agent-router")
                continue
            changes.append(f"updated .claude/agents/{name}")
        else:
            changes.append(f"created .claude/agents/{name}")
        path.write_text(content, encoding="utf-8")
    for path in sorted(directory.glob(f"{PROJECT_AGENT_PREFIX}*.md")):
        if path.name not in wanted and MARKER in path.read_text(encoding="utf-8"):
            path.unlink()
            changes.append(f"removed .claude/agents/{path.name}")
    return changes
